import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "primary-fixed": "#ffdcc2",
        "surface-tint": "#8f4e00",
        "on-primary-fixed-variant": "#6d3a00",
        "error": "#ba1a1a",
        "inverse-surface": "#2f312f",
        "tertiary": "#b52619",
        "on-tertiary-fixed": "#410000",
        "on-error-container": "#93000a",
        "surface": "#faf9f6",
        "on-secondary": "#ffffff",
        "on-primary-container": "#693800",
        "on-primary-fixed": "#2e1500",
        "error-container": "#ffdad6",
        "surface-container-high": "#e9e8e5",
        "on-secondary-container": "#745c00",
        "on-secondary-fixed": "#241a00",
        "on-surface": "#1a1c1a",
        "surface-container": "#efeeeb",
        "outline": "#887364",
        "on-surface-variant": "#554336",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a8",
        "background": "#faf9f6",
        "on-tertiary-fixed-variant": "#920703",
        "on-tertiary": "#ffffff",
        "primary": "#8f4e00",
        "surface-variant": "#e3e2e0",
        "inverse-on-surface": "#f2f1ee",
        "outline-variant": "#dbc2b0",
        "tertiary-fixed": "#ffdad4",
        "surface-container-low": "#f4f3f1",
        "primary-container": "#ff9933",
        "inverse-primary": "#ffb77a",
        "secondary-fixed-dim": "#e9c349",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf9f6",
        "on-tertiary-container": "#8e0301",
        "secondary-container": "#fed65b",
        "on-background": "#1a1c1a",
        "tertiary-container": "#ff9585",
        "primary-fixed-dim": "#ffb77a",
        "surface-container-highest": "#e3e2e0",
        "secondary-fixed": "#ffe088",
        "secondary": "#735c00",
        "on-secondary-fixed-variant": "#574500",
        "surface-dim": "#dbdad7",
        "saffron": "#f28c28",
        "gold": "#d4af37"
      },
      fontFamily: {
        "headline": ["var(--font-noto-serif)", "Noto Serif", "serif"],
        "body": ["var(--font-public-sans)", "Public Sans", "sans-serif"],
        "label": ["var(--font-public-sans)", "Public Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "temple": "2rem 2rem 0.5rem 0.5rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
export default config;
